controller_manager:
  ros__parameters:
    update_rate: 10

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_link1_joint
      - link1_link2_joint
      - link2_link3_joint
      - link3_link4_joint
      - link4_link5_joint
      - link5_link6_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

